client_type: openai
# The base URL of the API
base_url: https://api.groq.com/openai/v1
# get your api key from the environment variable GROQ_API_KEY
api_key: ${oc.env:GROQ_API_KEY}
# the maximum number of concurrent requests to the API
max_concurrency: 1
# see: https://console.groq.com/docs/api-reference for more detail
params:
  model: llama-3.2-3b-preview
  max_tokens: 4096