# Path to the file containing the list of book pages
books: books.txt
# config filename in configs/clients
client_cfg: groq.yaml
# Number of reviews to request per chunk
reviews_per_chunk: 100
# Maximum number of reviews to scrape per book for each star rating
max_reviews: 100
# Interval between requests to the Goodreads API in seconds
interval: 2
# output language of the final summary
language: English
# The directory to save the output
output_dir: ./output
# Save intermediate data
save_tmp: false
# Use intermediate data
use_tmp: false