# Path to the file containing the list of book pages
books: books.txt
# client config in configs/clients
client: ollama.yaml
# settings for scrapping the book platforms
platform: platform.yaml
# output language of the final summary
language: English
# The directory to save the output
output_dir: ./output
# set to "total" to generate one summary for all ratings, or "rating" to generate separate summaries for each rating
summary_mode: total
# Save intermediate data
save_tmp: false
# Use intermediate data
use_tmp: false
# Use HDBSCAN algorithm to cluster reviews before summarizing
clustering: false
# When enable clustering, visualize and save the plot
viz_clusters: false
# random seed
seed: 0
# use for dimensionality reduction during clustering
pca:
  n_components: 50
# use for clustering
hdbscan:
  min_cluster_size: 10
  min_samples: 5
  metric: cosine
# use for visualizing clusters
umap:
  metric: cosine
  n_neighbors: 10
  min_dist: 0.1