# Path to the file containing the list of book pages
books: books.txt
# client config in configs/clients
client: ollama.yaml
# Number of reviews to request per chunk
reviews_per_chunk: 100
# Maximum number of reviews to scrape per book for each star rating
max_reviews: 100
# Interval between requests to the Goodreads API in seconds
interval: 2
# output language of the final summary
language: English
# The directory to save the output
output_dir: ./output
# Save intermediate data
save_tmp: false
# Use intermediate data
use_tmp: false
# Use HDBSCAN algorithm to cluster reviews before summarizing
clustering: false
# When enable clustering, visualize and save the plot
viz_clusters: false
# random seed
seed: 0
# use for dimensionality reduction during clustering
pca:
  n_components: 50
# use for clustering
hdbscan:
  min_cluster_size: 10
  min_samples: 5
  metric: cosine
# use for visualizing clusters
umap:
  metric: cosine
  n_neighbors: 10
  min_dist: 0.1